<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>5fdd6c37-edd5-4e5e-abdd-c6ecc5caafb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.px-4.mb-sm-0.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e84f24dc-cf48-46c8-bd24-efd2ad6c2b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21b42f53-e343-4bae-abe1-05bf4c046bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary px-4 mb-sm-0 ng-star-inserted</value>
      <webElementGuid>1eedc14e-3049-433f-a417-0a2c82bf18d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>f40e19c7-fd93-4c19-bcb9-a3af2c689ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageHeader&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;pageHeader py-3&quot;]/div[@class=&quot;row align-items-center h-100&quot;]/div[@class=&quot;col-md-12 col-lg-8 mt-2 mt-lg-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;px-2 d-flex ml-auto&quot;]/div[@class=&quot;ml-auto ng-star-inserted&quot;]/button[@class=&quot;btn btn-secondary px-4 mb-sm-0 ng-star-inserted&quot;]</value>
      <webElementGuid>b8a1773a-ad90-47b7-9cae-9cc2f804e72d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>29b31b2e-7458-4040-ac91-27da00dcf6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageHeader']/div/div/div/div/div/div[2]/div/div/div/button[2]</value>
      <webElementGuid>aa7ad7a9-d20a-4264-96d1-79fe16f0491e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[1]</value>
      <webElementGuid>88bd9f2a-aaee-474b-b15d-0ce39c6997d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/following::button[2]</value>
      <webElementGuid>419dfad8-6eea-4816-a6c0-e3f7b317bc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incidents'])[1]/preceding::button[2]</value>
      <webElementGuid>0f68b4fd-fd2d-42dd-8285-d7864671eb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Information'])[1]/preceding::button[2]</value>
      <webElementGuid>a172f020-cc75-43ac-971e-50801057df84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button[2]</value>
      <webElementGuid>e331910d-7e12-462f-b5d9-5f805b4f7db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>d2da79ec-fbf8-4116-9c21-37c7c807131c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
