<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1Incidents2Case Information3Participant_da2c49</name>
   <tag></tag>
   <elementGuidId>ad2eb008-956d-460f-a0c4-ca5b4277155e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex-fill.h-100.bg-white.pb-3.caseIntakePage-cont</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ab7702e-0947-47d6-825d-81554f4a515f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-fill h-100 bg-white pb-3 caseIntakePage-cont</value>
      <webElementGuid>d6cb6fcc-d653-4ded-a6ff-c25ef5c9dac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewLEA # *Offense From Date *ui-btnOffense To Dateui-btnLEA *SelectAgricultural Department Agricultural DepartmentFactsLocation DescriptionNotesAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status   No Records found Address Details Add Address  No Records found SaveCancel</value>
      <webElementGuid>adc0ea7b-877a-476a-84ec-55a43a0ba867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[1]/app-case-intake[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;d-block d-md-flex bg-white mb-3&quot;]/div[@class=&quot;flex-fill h-100 bg-white pb-3 caseIntakePage-cont&quot;]</value>
      <webElementGuid>39e5a241-573f-44f8-a87a-27d04ee4f100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div</value>
      <webElementGuid>fcd6c6fd-f316-4c28-9c96-0ce73ac4d8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::div[5]</value>
      <webElementGuid>f5d10c09-df43-4200-9f0c-a48e27283a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[5]</value>
      <webElementGuid>fdbcf8f6-b802-4e43-b9e8-51fd34c3ad09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-case-intake/div[2]/div/div/div/div</value>
      <webElementGuid>0c02f499-20b3-467e-8319-c537b06dad0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewLEA # *Offense From Date *ui-btnOffense To Dateui-btnLEA *SelectAgricultural Department Agricultural DepartmentFactsLocation DescriptionNotesAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status   No Records found Address Details Add Address  No Records found SaveCancel' or . = '1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewLEA # *Offense From Date *ui-btnOffense To Dateui-btnLEA *SelectAgricultural Department Agricultural DepartmentFactsLocation DescriptionNotesAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status   No Records found Address Details Add Address  No Records found SaveCancel')]</value>
      <webElementGuid>78ab47ff-d822-48c0-ab9a-cce82ca17df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
