<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Staff TypeSelectSelectAssignment Begin _fdc4f2 (1)</name>
   <tag></tag>
   <elementGuidId>b5151bc9-cd6f-40a3-afe4-ed74f23112a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/div/app-assigned-staff/roots-dialog/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-dialog-content.ui-widget-content.ng-tns-c50-180</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1ad95ae-d808-4b2b-85b6-520c7c645311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dialog-content ui-widget-content ng-tns-c50-180</value>
      <webElementGuid>0baf1f5a-6291-49f9-9283-fb0702398e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Staff Type*SelectSelectAssignment Begin Date*ui-btnAssigned To*SelectSelectAssigned To is required.Assignment End Dateui-btnAssigned BySelectSelectParticipants (To assign at case level, do not select participants)ChooseSaveCancel</value>
      <webElementGuid>0956b294-01b1-4347-ab09-6ebbef1fd584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[1]/app-case-intake[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;d-block d-md-flex bg-white mb-3&quot;]/div[@class=&quot;flex-fill h-100 bg-white pb-3 caseIntakePage-cont&quot;]/div[@class=&quot;bg-white mb-3&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;d-block d-md-flex&quot;]/div[@class=&quot;row flex-fill h-100 bg-white position-relative caseIntakePage-cont&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/div[@class=&quot;mb-2 ng-star-inserted&quot;]/app-assigned-staff[1]/roots-dialog[@class=&quot;ng-tns-c50-180 ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c50-180 col-md-10 col-lg-10 col-xl-8 px-0 ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-dialog-resizable ng-star-inserted ng-animating&quot;]/div[@class=&quot;ui-dialog-content ui-widget-content ng-tns-c50-180&quot;]</value>
      <webElementGuid>4bc3b437-3f1c-4aff-ba70-772bd2242a4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/div/app-assigned-staff/roots-dialog/div/div[2]</value>
      <webElementGuid>30fe9de5-d60a-46c0-9469-5f3b5a31711c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Assigned Staff'])[2]/following::div[1]</value>
      <webElementGuid>73529d7e-1165-48c7-9535-1fc69cce4afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::div[3]</value>
      <webElementGuid>90cbb7c5-4e4f-4963-a9a3-19cd0b676f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//roots-dialog/div/div[2]</value>
      <webElementGuid>28847427-86a1-455a-ad3a-3faf71b20f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Staff Type*SelectSelectAssignment Begin Date*ui-btnAssigned To*SelectSelectAssigned To is required.Assignment End Dateui-btnAssigned BySelectSelectParticipants (To assign at case level, do not select participants)ChooseSaveCancel' or . = 'Staff Type*SelectSelectAssignment Begin Date*ui-btnAssigned To*SelectSelectAssigned To is required.Assignment End Dateui-btnAssigned BySelectSelectParticipants (To assign at case level, do not select participants)ChooseSaveCancel')]</value>
      <webElementGuid>a4fe2e0d-0e7d-496a-bbb4-6c8eee66f8aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
