<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PrintPreviousNext</name>
   <tag></tag>
   <elementGuidId>756993cd-df25-4f38-9a4e-f954a06ab61e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageHeader']/div/div/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-12.col-lg-8.mt-2.mt-lg-0 > div.row</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>278691b5-4150-4485-a11e-680bce2e5f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>19c12f0e-1895-4b50-90a1-f42577a17829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PrintPreviousNext×</value>
      <webElementGuid>0a159f7d-831b-4c61-9d3b-f6a6e463dcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageHeader&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;pageHeader py-3&quot;]/div[@class=&quot;row align-items-center h-100&quot;]/div[@class=&quot;col-md-12 col-lg-8 mt-2 mt-lg-0&quot;]/div[@class=&quot;row&quot;]</value>
      <webElementGuid>6aaf2aec-0a22-4288-abc4-e845570208f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageHeader']/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>a55cc911-401e-49f6-847c-83fc61283953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case'])[1]/following::div[3]</value>
      <webElementGuid>1afb7e0e-8e54-4ba2-afa0-661e5401a8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-case-intake/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>eabe1163-ffc2-4812-9b21-b6a261e74330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PrintPreviousNext×' or . = 'PrintPreviousNext×')]</value>
      <webElementGuid>d6d90506-f4d8-4ce3-8663-9ba4ae7edb58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
