<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Partial StatuteOffense Title_partialStatute</name>
   <tag></tag>
   <elementGuidId>b8ebc100-0ca6-4c12-aa73-15a6694ea7f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#partialStatute</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partialStatute']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0b4c61b-e40b-4305-85d1-a93d62c19816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97e99769-0dce-495c-b518-1a0a4579aa19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partialStatute</value>
      <webElementGuid>9257f317-7f89-4b66-9e37-befc2932ac04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>partialStatute</value>
      <webElementGuid>1d6cad88-523f-45c0-b72b-535596225c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type Here</value>
      <webElementGuid>b9743ebd-fabf-4e1d-912c-ff6bd278da99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>6ee07c94-d8ff-4473-9222-9a85c94ebfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partialStatute&quot;)</value>
      <webElementGuid>58c110c5-c4c2-4adb-a1f0-448cf5ce840c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partialStatute']</value>
      <webElementGuid>e3a38627-bf2d-471a-ae54-8695bfe3a7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/app-caseintake-charges/div[2]/app-participant-addcharges/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>f0607f47-dc90-4632-8321-ef8f96da2b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>1823a545-5d68-4a39-8c61-5b7269b07cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'partialStatute' and @placeholder = 'Type Here']</value>
      <webElementGuid>f68d1069-4795-4e29-8538-cd79729e2647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
