<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Offense To Date_EndDate (1)</name>
   <tag></tag>
   <elementGuidId>727122cc-194a-44ae-bee8-6fd225f601d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EndDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EndDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7cfc4957-757a-420b-b52f-e26011de4ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0f3b89c-7afb-4e03-a2d4-bf8f9544d1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d1e10a2-df61-4f1b-b4c5-b939e562b4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c62-37 ui-inputtext ui-widget ui-state-default ui-corner-all ng-star-inserted</value>
      <webElementGuid>6cb170c6-e881-4d75-83bf-50da880e36c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>adcfc044-faca-4012-b103-92e05b93105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>EndDate</value>
      <webElementGuid>42328e33-aafe-43f6-a550-7c310bd5c25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EndDate</value>
      <webElementGuid>19b3f4cd-b1b0-480c-802b-41949235f5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EndDate&quot;)</value>
      <webElementGuid>a7fcdf89-a1bb-49e8-b6c2-803acc4c8264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EndDate']</value>
      <webElementGuid>dd76ca47-c197-486d-87b6-0ecffa1f44b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='test']/div/div/form/div/div/div[2]/div/div[3]/div/roots-calendar/span/input</value>
      <webElementGuid>951398fa-28b0-4190-986c-f31a3a728b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/roots-calendar/span/input</value>
      <webElementGuid>7cf969d3-dcc0-4113-ad22-2b72908d5aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'MM/DD/YYYY' and @id = 'EndDate']</value>
      <webElementGuid>72ead059-a0d2-4455-a7f9-f69fa47465af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
