<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main_HomeCaseCase Intake  - Adult CriminalP_521fef</name>
   <tag></tag>
   <elementGuidId>b9e8fb54-2520-49ec-bfb0-abf444509af4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>f61ffd82-a14e-4761-af24-e58798c831f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>bb1f751c-adeb-4b21-8046-6648b7a316d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>78d5550f-dbe3-4bf3-9021-fab03efffa65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white</value>
      <webElementGuid>a8215eea-c008-4c2d-9289-b5a3c3aac362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeCaseCase Intake  - Adult CriminalPrintPreviousNext×1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewCase InformationIs Sensitive CaseIntake Type *SelectFelony FelonyOffense Category SelectSelectCase Flags _Restitution: Applicable_Restitution: Applicable_Restitution: NOT ApplicableAccident IndicatorAlbina Gang ProjectAuto Theft Task ForceBallot Measure 11Ballot Measure 73BM11 charges reduced to non-BM11 chargesBody Worn CameraBurglary Task ForceCA_Bradley Angle HouseCA_DART - Disability Awareness Resource TeamCA_Gateway CenterCA_IRCO - Immigrant and Refugee Community OrganizationCA_SVU - Special Victims UnitCase Disposition Letter to be sent to WitnessesCommercial TheftCOPS - GRANTCOPS - METHCriminal ForfeitureDANY GrantDD/Mental Health Disabled VictimDomestic ViolenceDowntown Neighborhood Prosecution UnitDrug Endangered Child CaseDrug Free ZoneDrug Residue CaseDV Enhanced Response Team (DVERT)DVD CaseEast Burglary Intervention CaseEast Precinct Neighborhood Prosecution UnitElder Abuse CaseFASTGang RelatedGateway Center CaseGraffiti TagGresham Misdemeanor UnitGresham Neighborhood Prosecution UnitGun Task ForceGUNS - Case involves the use of firearmsHomicideHuman Trafficking TeamInjury IndicatorIntake UnitJail Crimes OffenseJessica's LawJuvenile Accountability Block GrantLloyd Center Neighborhood Prosecution UnitMass Demonstration CaseMAVMDTMedical Marijuana CaseMisd Case Felony DDAMotor Vehicle OffenseNeighborhood Livability CEPNorth Precinct Neighborhood Prosecution UnitNPC Research Project (DV)Operation MaterOperation Neighborhood ReliefOperation Street SweepOverdose DeathProbation Violation Notification to VictimProject FuntProperty Damage IndicatorProstitution Free ZoneProstitution Neighborhood Prosecution UnitPSI OrderedPSU StudyReferred from Juvenile Court for ProsecutionRound 2 (UB Cases)Round 3 (UB Cases)Round 4 (UB Cases)SealedSecret IndictmentSIU CaseSoutheast Precinct Neighborhood Prosecution UnitSpecial Assignment to Misdemeanor DDASPSU CaseTri-Met Neighborhood Prosecution UnitUnit X CaseVehicular HomicideVictim is a JuvenileViolation of Restraining OrderViolation TreatmentViolence Against Women ActWarrant Service ProjectWhite Collar Crime TeamCourt *SelectCircuit Court Circuit CourtCourt Facility SelectSelectJudge SelectSelectReceived Date *ui-btnCase Summary Case Detail SummaryAdd Case Detail Case Detail Type  Case Detail  No Records found Related Cases SummaryAdd Related Cases Case  Case Title  Case Status  Relationship Reason   No Records found KeywordsAdd Keywords Keywords Expansion Header No Records found PreviousNext</value>
      <webElementGuid>0dc8effb-868e-4cd2-8569-a4a67ac04eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)</value>
      <webElementGuid>7d7c1642-ce49-4b80-b6f9-3d9752f90071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//main[@id='main']</value>
      <webElementGuid>42f19a3b-a308-4763-ad22-008809315892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advance Filter'])[1]/following::main[1]</value>
      <webElementGuid>a4d1a9c8-ca0b-4693-a895-641a9c2043b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='label for searchText'])[2]/following::main[1]</value>
      <webElementGuid>23dc0539-2eac-4f85-b5dd-dc8eacf98a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main</value>
      <webElementGuid>1c4dfc78-6bb9-4488-bec7-d0ca71354c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//main[@id = 'main' and (text() = concat(&quot;HomeCaseCase Intake  - Adult CriminalPrintPreviousNext×1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewCase InformationIs Sensitive CaseIntake Type *SelectFelony FelonyOffense Category SelectSelectCase Flags _Restitution: Applicable_Restitution: Applicable_Restitution: NOT ApplicableAccident IndicatorAlbina Gang ProjectAuto Theft Task ForceBallot Measure 11Ballot Measure 73BM11 charges reduced to non-BM11 chargesBody Worn CameraBurglary Task ForceCA_Bradley Angle HouseCA_DART - Disability Awareness Resource TeamCA_Gateway CenterCA_IRCO - Immigrant and Refugee Community OrganizationCA_SVU - Special Victims UnitCase Disposition Letter to be sent to WitnessesCommercial TheftCOPS - GRANTCOPS - METHCriminal ForfeitureDANY GrantDD/Mental Health Disabled VictimDomestic ViolenceDowntown Neighborhood Prosecution UnitDrug Endangered Child CaseDrug Free ZoneDrug Residue CaseDV Enhanced Response Team (DVERT)DVD CaseEast Burglary Intervention CaseEast Precinct Neighborhood Prosecution UnitElder Abuse CaseFASTGang RelatedGateway Center CaseGraffiti TagGresham Misdemeanor UnitGresham Neighborhood Prosecution UnitGun Task ForceGUNS - Case involves the use of firearmsHomicideHuman Trafficking TeamInjury IndicatorIntake UnitJail Crimes OffenseJessica&quot; , &quot;'&quot; , &quot;s LawJuvenile Accountability Block GrantLloyd Center Neighborhood Prosecution UnitMass Demonstration CaseMAVMDTMedical Marijuana CaseMisd Case Felony DDAMotor Vehicle OffenseNeighborhood Livability CEPNorth Precinct Neighborhood Prosecution UnitNPC Research Project (DV)Operation MaterOperation Neighborhood ReliefOperation Street SweepOverdose DeathProbation Violation Notification to VictimProject FuntProperty Damage IndicatorProstitution Free ZoneProstitution Neighborhood Prosecution UnitPSI OrderedPSU StudyReferred from Juvenile Court for ProsecutionRound 2 (UB Cases)Round 3 (UB Cases)Round 4 (UB Cases)SealedSecret IndictmentSIU CaseSoutheast Precinct Neighborhood Prosecution UnitSpecial Assignment to Misdemeanor DDASPSU CaseTri-Met Neighborhood Prosecution UnitUnit X CaseVehicular HomicideVictim is a JuvenileViolation of Restraining OrderViolation TreatmentViolence Against Women ActWarrant Service ProjectWhite Collar Crime TeamCourt *SelectCircuit Court Circuit CourtCourt Facility SelectSelectJudge SelectSelectReceived Date *ui-btnCase Summary Case Detail SummaryAdd Case Detail Case Detail Type  Case Detail  No Records found Related Cases SummaryAdd Related Cases Case  Case Title  Case Status  Relationship Reason   No Records found KeywordsAdd Keywords Keywords Expansion Header No Records found PreviousNext&quot;) or . = concat(&quot;HomeCaseCase Intake  - Adult CriminalPrintPreviousNext×1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewCase InformationIs Sensitive CaseIntake Type *SelectFelony FelonyOffense Category SelectSelectCase Flags _Restitution: Applicable_Restitution: Applicable_Restitution: NOT ApplicableAccident IndicatorAlbina Gang ProjectAuto Theft Task ForceBallot Measure 11Ballot Measure 73BM11 charges reduced to non-BM11 chargesBody Worn CameraBurglary Task ForceCA_Bradley Angle HouseCA_DART - Disability Awareness Resource TeamCA_Gateway CenterCA_IRCO - Immigrant and Refugee Community OrganizationCA_SVU - Special Victims UnitCase Disposition Letter to be sent to WitnessesCommercial TheftCOPS - GRANTCOPS - METHCriminal ForfeitureDANY GrantDD/Mental Health Disabled VictimDomestic ViolenceDowntown Neighborhood Prosecution UnitDrug Endangered Child CaseDrug Free ZoneDrug Residue CaseDV Enhanced Response Team (DVERT)DVD CaseEast Burglary Intervention CaseEast Precinct Neighborhood Prosecution UnitElder Abuse CaseFASTGang RelatedGateway Center CaseGraffiti TagGresham Misdemeanor UnitGresham Neighborhood Prosecution UnitGun Task ForceGUNS - Case involves the use of firearmsHomicideHuman Trafficking TeamInjury IndicatorIntake UnitJail Crimes OffenseJessica&quot; , &quot;'&quot; , &quot;s LawJuvenile Accountability Block GrantLloyd Center Neighborhood Prosecution UnitMass Demonstration CaseMAVMDTMedical Marijuana CaseMisd Case Felony DDAMotor Vehicle OffenseNeighborhood Livability CEPNorth Precinct Neighborhood Prosecution UnitNPC Research Project (DV)Operation MaterOperation Neighborhood ReliefOperation Street SweepOverdose DeathProbation Violation Notification to VictimProject FuntProperty Damage IndicatorProstitution Free ZoneProstitution Neighborhood Prosecution UnitPSI OrderedPSU StudyReferred from Juvenile Court for ProsecutionRound 2 (UB Cases)Round 3 (UB Cases)Round 4 (UB Cases)SealedSecret IndictmentSIU CaseSoutheast Precinct Neighborhood Prosecution UnitSpecial Assignment to Misdemeanor DDASPSU CaseTri-Met Neighborhood Prosecution UnitUnit X CaseVehicular HomicideVictim is a JuvenileViolation of Restraining OrderViolation TreatmentViolence Against Women ActWarrant Service ProjectWhite Collar Crime TeamCourt *SelectCircuit Court Circuit CourtCourt Facility SelectSelectJudge SelectSelectReceived Date *ui-btnCase Summary Case Detail SummaryAdd Case Detail Case Detail Type  Case Detail  No Records found Related Cases SummaryAdd Related Cases Case  Case Title  Case Status  Relationship Reason   No Records found KeywordsAdd Keywords Keywords Expansion Header No Records found PreviousNext&quot;))]</value>
      <webElementGuid>4781bb37-fd00-4fae-9e4e-660cfab37d1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
