<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose_ui-multiselect-trigger-icon ui-_dbe60d</name>
   <tag></tag>
   <elementGuidId>472b892d-1a51-475b-abb2-3849f52ad98b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-2-label']/div/form/div[2]/div/div[4]/div/roots-multiselect/div/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-multiselect-trigger-icon.ui-clickable.ng-tns-c52-51.fas.fa-angle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51549649-2720-4fd6-a6fe-49a8031ec88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-multiselect-trigger-icon ui-clickable ng-tns-c52-51 fas fa-angle-down</value>
      <webElementGuid>ee4e9f60-cbf9-44a9-a4c5-b4b43d9eaeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-2&quot;)/div[@id=&quot;ui-panel-2-label&quot;]/div[@class=&quot;ui-panel-content ui-widget-content ng-tns-c74-39&quot;]/form[@class=&quot;ng-tns-c74-39 ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;detail-tab&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-lg-4 col-xl-3 ng-star-inserted&quot;]/div[@class=&quot;form-group&quot;]/roots-multiselect[@class=&quot;roots-form-control ng-tns-c52-51 ui-inputwrapper-filled ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c52-51 ui-multiselect ui-widget ui-state-default ui-corner-all&quot;]/div[@class=&quot;ng-tns-c52-51 ui-multiselect-trigger ui-state-default ui-corner-right&quot;]/span[@class=&quot;ui-multiselect-trigger-icon ui-clickable ng-tns-c52-51 fas fa-angle-down&quot;]</value>
      <webElementGuid>4c3a0231-24c3-4363-851d-1381bf1aadbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-2-label']/div/form/div[2]/div/div[4]/div/roots-multiselect/div/div[3]/span</value>
      <webElementGuid>c2e662c8-a7d9-4c62-8b16-5c51e60c655f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/roots-multiselect/div/div[3]/span</value>
      <webElementGuid>dca6f633-f3f4-407d-857f-1c5916929386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
