<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_balya I, Pradeep kumar</name>
   <tag></tag>
   <elementGuidId>43fffca2-7f6e-4969-87a6-ca6662d9b40d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/app-caseinatake-review/div/div[2]/div[2]/app-roots-card-template/div/div[2]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>056d2c21-e328-44ee-8f20-591cb25fd2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-break</value>
      <webElementGuid>947e9398-a021-4bac-bd1a-f804f933b71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>balya I, Pradeep kumar</value>
      <webElementGuid>51ad4082-42a7-478a-91df-571eb77e6a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[1]/app-case-intake[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;d-block d-md-flex bg-white mb-3&quot;]/div[@class=&quot;flex-fill h-100 bg-white pb-3&quot;]/div[@class=&quot;bg-white mb-3&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;d-block d-md-flex&quot;]/div[@class=&quot;row flex-fill h-100 bg-white position-relative&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/app-caseinatake-review[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;review&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-12 mb-3 ng-star-inserted&quot;]/app-roots-card-template[1]/div[@class=&quot;roots-card-template h-100&quot;]/div[@class=&quot;ui-card-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row my-2 ng-star-inserted&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;d-flex&quot;]/span[@class=&quot;text-break&quot;]</value>
      <webElementGuid>4bd7bd68-7c46-4abc-ad0f-1f8c3502a4ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/app-caseinatake-review/div/div[2]/div[2]/app-roots-card-template/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>00516756-073b-43d2-9cd9-c7376cbb3f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned By :'])[1]/following::span[1]</value>
      <webElementGuid>fd01f577-92a0-4e16-ae89-499eea055b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='edit'])[2]/following::span[1]</value>
      <webElementGuid>1e8964b4-772c-4247-8ccb-5301f1043a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment Begin Date :'])[1]/preceding::span[1]</value>
      <webElementGuid>cf9549fa-4a92-4851-a706-349c93c875b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment End Date :'])[1]/preceding::span[2]</value>
      <webElementGuid>51fd775b-4a6a-4643-9526-d8459e1fba95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/app-roots-card-template/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>8959fb72-d5d8-4d71-998c-5d01d87f3791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'balya I, Pradeep kumar' or . = 'balya I, Pradeep kumar')]</value>
      <webElementGuid>3dcae49d-9d3a-46f4-acfd-949e9c103a4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
